const products = [
  {
    id: "510216",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "873685",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "968760",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "047240",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "649653",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "632249",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "374483",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "341014",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "309592",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "702693",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "117405",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "147802",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "801473",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "568438",
    productName: "Nike Dunk High",
    description:
      "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with perfectly sheened overlays\n       and original university colors. With its classic hoops design, the Nike Dunk High Retro channels '80s vintage back\n        onto the streets while its padded, high-top collar adds an old-school look rooted in comfort.",
    category: "shoes",
    imagePath: "../../frontend/public/images/Nike shoe.jpg",
    stock: 975,
    unitPrice: "$130",
    time: "2024-12-03T12:56:51.308Z",
  },
  {
    id: "235950",
    productName: "Air Jordan 1",
    description: "A cool nike shoe",
    price: "$140",
    stock: 14,
    time: "2024-12-03T12:56:58.145Z",
  },
  {
    id: "957516",
    productName: "Air Force 6",
    description: "A cool air force",
    price: "$240",
    stock: 14,
    time: "2024-12-09T09:23:09.753Z",
  },
  {
    id: "699104",
    productName: "Air Force 6",
    description: "A cool air force",
    price: "$240",
    stock: 14,
    time: "2024-12-09T09:24:34.167Z",
  },
  {
    id: "551691",
    productName: "New Balance 5",
    description: "Stylish shoe",
    price: "$120",
    stock: 10,
    time: "2024-12-09T15:59:02.270Z",
  },
];

export default products;
